import { Rule } from "@/types/spotify";

export const allGenres: string[] = [
    "acoustic",
    "afrobeat",
    "alt-rock",
    "alternative",
    "ambient",
    "anime",
    "black-metal",
    "bluegrass",
    "blues",
    "bossanova",
    "brazil",
    "breakbeat",
    "british",
    "cantopop",
    "chicago-house",
    "children",
    "chill",
    "classical",
    "club",
    "comedy",
    "country",
    "dance",
    "dancehall",
    "death-metal",
    "deep-house",
    "detroit-techno",
    "disco",
    "disney",
    "drum-and-bass",
    "dub",
    "dubstep",
    "edm",
    "electro",
    "electronic",
    "emo",
    "folk",
    "forro",
    "french",
    "funk",
    "garage",
    "german",
    "gospel",
    "goth",
    "grindcore",
    "groove",
    "grunge",
    "guitar",
    "happy",
    "hard-rock",
    "hardcore",
    "hardstyle",
    "heavy-metal",
    "hip-hop",
    "holidays",
    "honky-tonk",
    "house",
    "idm",
    "indian",
    "indie",
    "indie-pop",
    "industrial",
    "iranian",
    "j-dance",
    "j-idol",
    "j-pop",
    "j-rock",
    "jazz",
    "k-pop",
    "kids",
    "latin",
    "latino",
    "malay",
    "mandopop",
    "metal",
    "metal-misc",
    "metalcore",
    "minimal-techno",
    "movies",
    "mpb",
    "new-age",
    "new-release",
    "opera",
    "pagode",
    "party",
    "philippines-opm",
    "piano",
    "pop",
    "pop-film",
    "post-dubstep",
    "power-pop",
    "progressive-house",
    "psych-rock",
    "punk",
    "punk-rock",
    "r-n-b",
    "rainy-day",
    "reggae",
    "reggaeton",
    "road-trip",
    "rock",
    "rock-n-roll",
    "rockabilly",
    "romance",
    "sad",
    "salsa",
    "samba",
    "sertanejo",
    "show-tunes",
    "singer-songwriter",
    "ska",
    "sleep",
    "songwriter",
    "soul",
    "soundtracks",
    "spanish",
    "study",
    "summer",
    "swedish",
    "synth-pop",
    "tango",
    "techno",
    "trance",
    "trip-hop",
    "turkish",
    "work-out",
    "world-music",
];

export const allRules: Rule[] = [
    {
        name: "Danceability",
        type: "range",
        value: 50,
        range: ["Not Dancable", "Danceable"],
        description:
            "How suitable a track is for dancing based on a combination of musical elements including tempo, rhythm stability, beat strength, and overall regularity.",
    },
    {
        name: "Mood",
        type: "axis",
        value: [50, 50],
        range: [
            ["negative", "positive"],
            ["intense", "mild"],
        ],
        description:
            "Choose the Mood according to the Arousal-Valence model of emotions (Amount of Arousal and Valence of a Track).",
    },
    {
        name: "Instrumentalness",
        type: "range",
        value: 50,
        range: ["Vocal", "Instrumental"],
        description:
            "High value represents more instrumental tracks, low represents more vocals in tracks.",
    },
    {
        name: "Accousticness",
        type: "range",
        value: 50,
        range: ["Synthetic", "Accoustic"],
        description: "Whether the Song is accoustic or not.",
    },
    {
        name: "Liveness",
        type: "range",
        value: 50,
        range: ["Studio", "Live"],
        description:
            "Want to listen to live performances? Detects the presence of an audience in the recording. Higher liveness values represent an increased probability that the track was performed live. A value above 0.8 provides strong likelihood that the track is live.",
    },
    {
        name: "Popularity",
        type: "range",
        value: 50,
        range: ["Underground", "Mainstream"],
        description:
            "Want to filter out mainstream music? Or only listen to what others approved by listening to it? This is the right filter for you.",
    },
    {
        name: "Mode",
        type: "boolean",
        value: false,
        range: ["Minor", "Major"],
        description: "Choose between Tracks using Minor or Major mode.",
    },
    {
        name: "Tempo",
        type: "range",
        value: 100,
        range: ["40", "200"],
        description: "Choose the Tempo of the Track.",
    },
];
