import { Rule, Seed } from "@/types/spotify";

export const allGenres: string[] = [
    "acoustic",
    "afrobeat",
    "alt-rock",
    "alternative",
    "ambient",
    "anime",
    "black-metal",
    "bluegrass",
    "blues",
    "bossanova",
    "brazil",
    "breakbeat",
    "british",
    "cantopop",
    "chicago-house",
    "children",
    "chill",
    "classical",
    "club",
    "comedy",
    "country",
    "dance",
    "dancehall",
    "death-metal",
    "deep-house",
    "detroit-techno",
    "disco",
    "disney",
    "drum-and-bass",
    "dub",
    "dubstep",
    "edm",
    "electro",
    "electronic",
    "emo",
    "folk",
    "forro",
    "french",
    "funk",
    "garage",
    "german",
    "gospel",
    "goth",
    "grindcore",
    "groove",
    "grunge",
    "guitar",
    "happy",
    "hard-rock",
    "hardcore",
    "hardstyle",
    "heavy-metal",
    "hip-hop",
    "holidays",
    "honky-tonk",
    "house",
    "idm",
    "indian",
    "indie",
    "indie-pop",
    "industrial",
    "iranian",
    "j-dance",
    "j-idol",
    "j-pop",
    "j-rock",
    "jazz",
    "k-pop",
    "kids",
    "latin",
    "latino",
    "malay",
    "mandopop",
    "metal",
    "metal-misc",
    "metalcore",
    "minimal-techno",
    "movies",
    "mpb",
    "new-age",
    "new-release",
    "opera",
    "pagode",
    "party",
    "philippines-opm",
    "piano",
    "pop",
    "pop-film",
    "post-dubstep",
    "power-pop",
    "progressive-house",
    "psych-rock",
    "punk",
    "punk-rock",
    "r-n-b",
    "rainy-day",
    "reggae",
    "reggaeton",
    "road-trip",
    "rock",
    "rock-n-roll",
    "rockabilly",
    "romance",
    "sad",
    "salsa",
    "samba",
    "sertanejo",
    "show-tunes",
    "singer-songwriter",
    "ska",
    "sleep",
    "songwriter",
    "soul",
    "soundtracks",
    "spanish",
    "study",
    "summer",
    "swedish",
    "synth-pop",
    "tango",
    "techno",
    "trance",
    "trip-hop",
    "turkish",
    "work-out",
    "world-music",
];

export const allGenresSeeds: Seed[] = [
    {
        spotify: "todo: find genre links",
        id: "Acoustic",
        title: "Acoustic",
        description: "genre",
        type: "genre",
        thumbnail: 10,
    },
    {
        spotify: "todo: find genre links",
        id: "Afrobeat",
        title: "Afrobeat",
        description: "genre",
        type: "genre",
        thumbnail: 12,
    },
    {
        spotify: "todo: find genre links",
        id: "Alt-rock",
        title: "Alt-rock",
        description: "genre",
        type: "genre",
        thumbnail: 15,
    },
    {
        spotify: "todo: find genre links",
        id: "Alternative",
        title: "Alternative",
        description: "genre",
        type: "genre",
        thumbnail: 18,
    },
    {
        spotify: "todo: find genre links",
        id: "Ambient",
        title: "Ambient",
        description: "genre",
        type: "genre",
        thumbnail: 20,
    },
    {
        spotify: "todo: find genre links",
        id: "Anime",
        title: "Anime",
        description: "genre",
        type: "genre",
        thumbnail: 23,
    },
    {
        spotify: "todo: find genre links",
        id: "Black-metal",
        title: "Black-metal",
        description: "genre",
        type: "genre",
        thumbnail: 26,
    },
    {
        spotify: "todo: find genre links",
        id: "Bluegrass",
        title: "Bluegrass",
        description: "genre",
        type: "genre",
        thumbnail: 28,
    },
    {
        spotify: "todo: find genre links",
        id: "Blues",
        title: "Blues",
        description: "genre",
        type: "genre",
        thumbnail: 31,
    },
    {
        spotify: "todo: find genre links",
        id: "Bossanova",
        title: "Bossanova",
        description: "genre",
        type: "genre",
        thumbnail: 34,
    },
    {
        spotify: "todo: find genre links",
        id: "Brazil",
        title: "Brazil",
        description: "genre",
        type: "genre",
        thumbnail: 36,
    },
    {
        spotify: "todo: find genre links",
        id: "Breakbeat",
        title: "Breakbeat",
        description: "genre",
        type: "genre",
        thumbnail: 39,
    },
    {
        spotify: "todo: find genre links",
        id: "British",
        title: "British",
        description: "genre",
        type: "genre",
        thumbnail: 42,
    },
    {
        spotify: "todo: find genre links",
        id: "Cantopop",
        title: "Cantopop",
        description: "genre",
        type: "genre",
        thumbnail: 45,
    },
    {
        spotify: "todo: find genre links",
        id: "Chicago-house",
        title: "Chicago-house",
        description: "genre",
        type: "genre",
        thumbnail: 47,
    },
    {
        spotify: "todo: find genre links",
        id: "Children",
        title: "Children",
        description: "genre",
        type: "genre",
        thumbnail: 50,
    },
    {
        spotify: "todo: find genre links",
        id: "Chill",
        title: "Chill",
        description: "genre",
        type: "genre",
        thumbnail: 53,
    },
    {
        spotify: "todo: find genre links",
        id: "Classical",
        title: "Classical",
        description: "genre",
        type: "genre",
        thumbnail: 55,
    },
    {
        spotify: "todo: find genre links",
        id: "Club",
        title: "Club",
        description: "genre",
        type: "genre",
        thumbnail: 58,
    },
    {
        spotify: "todo: find genre links",
        id: "Comedy",
        title: "Comedy",
        description: "genre",
        type: "genre",
        thumbnail: 61,
    },
    {
        spotify: "todo: find genre links",
        id: "Country",
        title: "Country",
        description: "genre",
        type: "genre",
        thumbnail: 63,
    },
    {
        spotify: "todo: find genre links",
        id: "Dance",
        title: "Dance",
        description: "genre",
        type: "genre",
        thumbnail: 66,
    },
    {
        spotify: "todo: find genre links",
        id: "Dancehall",
        title: "Dancehall",
        description: "genre",
        type: "genre",
        thumbnail: 69,
    },
    {
        spotify: "todo: find genre links",
        id: "Death-metal",
        title: "Death-metal",
        description: "genre",
        type: "genre",
        thumbnail: 72,
    },
    {
        spotify: "todo: find genre links",
        id: "Deep-house",
        title: "Deep-house",
        description: "genre",
        type: "genre",
        thumbnail: 74,
    },
    {
        spotify: "todo: find genre links",
        id: "Detroit-techno",
        title: "Detroit-techno",
        description: "genre",
        type: "genre",
        thumbnail: 77,
    },
    {
        spotify: "todo: find genre links",
        id: "Disco",
        title: "Disco",
        description: "genre",
        type: "genre",
        thumbnail: 80,
    },
    {
        spotify: "todo: find genre links",
        id: "Disney",
        title: "Disney",
        description: "genre",
        type: "genre",
        thumbnail: 82,
    },
    {
        spotify: "todo: find genre links",
        id: "Drum-and-bass",
        title: "Drum-and-bass",
        description: "genre",
        type: "genre",
        thumbnail: 85,
    },
    {
        spotify: "todo: find genre links",
        id: "Dub",
        title: "Dub",
        description: "genre",
        type: "genre",
        thumbnail: 88,
    },
    {
        spotify: "todo: find genre links",
        id: "Dubstep",
        title: "Dubstep",
        description: "genre",
        type: "genre",
        thumbnail: 90,
    },
    {
        spotify: "todo: find genre links",
        id: "Edm",
        title: "Edm",
        description: "genre",
        type: "genre",
        thumbnail: 93,
    },
    {
        spotify: "todo: find genre links",
        id: "Electro",
        title: "Electro",
        description: "genre",
        type: "genre",
        thumbnail: 96,
    },
    {
        spotify: "todo: find genre links",
        id: "Electronic",
        title: "Electronic",
        description: "genre",
        type: "genre",
        thumbnail: 99,
    },
    {
        spotify: "todo: find genre links",
        id: "Emo",
        title: "Emo",
        description: "genre",
        type: "genre",
        thumbnail: 101,
    },
    {
        spotify: "todo: find genre links",
        id: "Folk",
        title: "Folk",
        description: "genre",
        type: "genre",
        thumbnail: 104,
    },
    {
        spotify: "todo: find genre links",
        id: "Forro",
        title: "Forro",
        description: "genre",
        type: "genre",
        thumbnail: 107,
    },
    {
        spotify: "todo: find genre links",
        id: "French",
        title: "French",
        description: "genre",
        type: "genre",
        thumbnail: 109,
    },
    {
        spotify: "todo: find genre links",
        id: "Funk",
        title: "Funk",
        description: "genre",
        type: "genre",
        thumbnail: 112,
    },
    {
        spotify: "todo: find genre links",
        id: "Garage",
        title: "Garage",
        description: "genre",
        type: "genre",
        thumbnail: 115,
    },
    {
        spotify: "todo: find genre links",
        id: "German",
        title: "German",
        description: "genre",
        type: "genre",
        thumbnail: 117,
    },
    {
        spotify: "todo: find genre links",
        id: "Gospel",
        title: "Gospel",
        description: "genre",
        type: "genre",
        thumbnail: 120,
    },
    {
        spotify: "todo: find genre links",
        id: "Goth",
        title: "Goth",
        description: "genre",
        type: "genre",
        thumbnail: 123,
    },
    {
        spotify: "todo: find genre links",
        id: "Grindcore",
        title: "Grindcore",
        description: "genre",
        type: "genre",
        thumbnail: 126,
    },
    {
        spotify: "todo: find genre links",
        id: "Groove",
        title: "Groove",
        description: "genre",
        type: "genre",
        thumbnail: 128,
    },
    {
        spotify: "todo: find genre links",
        id: "Grunge",
        title: "Grunge",
        description: "genre",
        type: "genre",
        thumbnail: 131,
    },
    {
        spotify: "todo: find genre links",
        id: "Guitar",
        title: "Guitar",
        description: "genre",
        type: "genre",
        thumbnail: 134,
    },
    {
        spotify: "todo: find genre links",
        id: "Happy",
        title: "Happy",
        description: "genre",
        type: "genre",
        thumbnail: 136,
    },
    {
        spotify: "todo: find genre links",
        id: "Hard-rock",
        title: "Hard-rock",
        description: "genre",
        type: "genre",
        thumbnail: 139,
    },
    {
        spotify: "todo: find genre links",
        id: "Hardcore",
        title: "Hardcore",
        description: "genre",
        type: "genre",
        thumbnail: 142,
    },
    {
        spotify: "todo: find genre links",
        id: "Hardstyle",
        title: "Hardstyle",
        description: "genre",
        type: "genre",
        thumbnail: 144,
    },
    {
        spotify: "todo: find genre links",
        id: "Heavy-metal",
        title: "Heavy-metal",
        description: "genre",
        type: "genre",
        thumbnail: 147,
    },
    {
        spotify: "todo: find genre links",
        id: "Hip-hop",
        title: "Hip-hop",
        description: "genre",
        type: "genre",
        thumbnail: 150,
    },
    {
        spotify: "todo: find genre links",
        id: "Holidays",
        title: "Holidays",
        description: "genre",
        type: "genre",
        thumbnail: 153,
    },
    {
        spotify: "todo: find genre links",
        id: "Honky-tonk",
        title: "Honky-tonk",
        description: "genre",
        type: "genre",
        thumbnail: 155,
    },
    {
        spotify: "todo: find genre links",
        id: "House",
        title: "House",
        description: "genre",
        type: "genre",
        thumbnail: 158,
    },
    {
        spotify: "todo: find genre links",
        id: "Idm",
        title: "Idm",
        description: "genre",
        type: "genre",
        thumbnail: 161,
    },
    {
        spotify: "todo: find genre links",
        id: "Indian",
        title: "Indian",
        description: "genre",
        type: "genre",
        thumbnail: 163,
    },
    {
        spotify: "todo: find genre links",
        id: "Indie",
        title: "Indie",
        description: "genre",
        type: "genre",
        thumbnail: 166,
    },
    {
        spotify: "todo: find genre links",
        id: "Indie-pop",
        title: "Indie-pop",
        description: "genre",
        type: "genre",
        thumbnail: 169,
    },
    {
        spotify: "todo: find genre links",
        id: "Industrial",
        title: "Industrial",
        description: "genre",
        type: "genre",
        thumbnail: 171,
    },
    {
        spotify: "todo: find genre links",
        id: "Iranian",
        title: "Iranian",
        description: "genre",
        type: "genre",
        thumbnail: 174,
    },
    {
        spotify: "todo: find genre links",
        id: "J-dance",
        title: "J-dance",
        description: "genre",
        type: "genre",
        thumbnail: 177,
    },
    {
        spotify: "todo: find genre links",
        id: "J-idol",
        title: "J-idol",
        description: "genre",
        type: "genre",
        thumbnail: 180,
    },
    {
        spotify: "todo: find genre links",
        id: "J-pop",
        title: "J-pop",
        description: "genre",
        type: "genre",
        thumbnail: 182,
    },
    {
        spotify: "todo: find genre links",
        id: "J-rock",
        title: "J-rock",
        description: "genre",
        type: "genre",
        thumbnail: 185,
    },
    {
        spotify: "todo: find genre links",
        id: "Jazz",
        title: "Jazz",
        description: "genre",
        type: "genre",
        thumbnail: 188,
    },
    {
        spotify: "todo: find genre links",
        id: "K-pop",
        title: "K-pop",
        description: "genre",
        type: "genre",
        thumbnail: 190,
    },
    {
        spotify: "todo: find genre links",
        id: "Kids",
        title: "Kids",
        description: "genre",
        type: "genre",
        thumbnail: 193,
    },
    {
        spotify: "todo: find genre links",
        id: "Latin",
        title: "Latin",
        description: "genre",
        type: "genre",
        thumbnail: 196,
    },
    {
        spotify: "todo: find genre links",
        id: "Latino",
        title: "Latino",
        description: "genre",
        type: "genre",
        thumbnail: 198,
    },
    {
        spotify: "todo: find genre links",
        id: "Malay",
        title: "Malay",
        description: "genre",
        type: "genre",
        thumbnail: 201,
    },
    {
        spotify: "todo: find genre links",
        id: "Mandopop",
        title: "Mandopop",
        description: "genre",
        type: "genre",
        thumbnail: 204,
    },
    {
        spotify: "todo: find genre links",
        id: "Metal",
        title: "Metal",
        description: "genre",
        type: "genre",
        thumbnail: 206,
    },
    {
        spotify: "todo: find genre links",
        id: "Metal-misc",
        title: "Metal-misc",
        description: "genre",
        type: "genre",
        thumbnail: 209,
    },
    {
        spotify: "todo: find genre links",
        id: "Metalcore",
        title: "Metalcore",
        description: "genre",
        type: "genre",
        thumbnail: 212,
    },
    {
        spotify: "todo: find genre links",
        id: "Minimal-techno",
        title: "Minimal-techno",
        description: "genre",
        type: "genre",
        thumbnail: 215,
    },
    {
        spotify: "todo: find genre links",
        id: "Movies",
        title: "Movies",
        description: "genre",
        type: "genre",
        thumbnail: 217,
    },
    {
        spotify: "todo: find genre links",
        id: "Mpb",
        title: "Mpb",
        description: "genre",
        type: "genre",
        thumbnail: 220,
    },
    {
        spotify: "todo: find genre links",
        id: "New-age",
        title: "New-age",
        description: "genre",
        type: "genre",
        thumbnail: 223,
    },
    {
        spotify: "todo: find genre links",
        id: "New-release",
        title: "New-release",
        description: "genre",
        type: "genre",
        thumbnail: 225,
    },
    {
        spotify: "todo: find genre links",
        id: "Opera",
        title: "Opera",
        description: "genre",
        type: "genre",
        thumbnail: 228,
    },
    {
        spotify: "todo: find genre links",
        id: "Pagode",
        title: "Pagode",
        description: "genre",
        type: "genre",
        thumbnail: 231,
    },
    {
        spotify: "todo: find genre links",
        id: "Party",
        title: "Party",
        description: "genre",
        type: "genre",
        thumbnail: 233,
    },
    {
        spotify: "todo: find genre links",
        id: "Philippines-opm",
        title: "Philippines-opm",
        description: "genre",
        type: "genre",
        thumbnail: 236,
    },
    {
        spotify: "todo: find genre links",
        id: "Piano",
        title: "Piano",
        description: "genre",
        type: "genre",
        thumbnail: 239,
    },
    {
        spotify: "todo: find genre links",
        id: "Pop",
        title: "Pop",
        description: "genre",
        type: "genre",
        thumbnail: 242,
    },
    {
        spotify: "todo: find genre links",
        id: "Pop-film",
        title: "Pop-film",
        description: "genre",
        type: "genre",
        thumbnail: 244,
    },
    {
        spotify: "todo: find genre links",
        id: "Post-dubstep",
        title: "Post-dubstep",
        description: "genre",
        type: "genre",
        thumbnail: 247,
    },
    {
        spotify: "todo: find genre links",
        id: "Power-pop",
        title: "Power-pop",
        description: "genre",
        type: "genre",
        thumbnail: 250,
    },
    {
        spotify: "todo: find genre links",
        id: "Progressive-house",
        title: "Progressive-house",
        description: "genre",
        type: "genre",
        thumbnail: 252,
    },
    {
        spotify: "todo: find genre links",
        id: "Psych-rock",
        title: "Psych-rock",
        description: "genre",
        type: "genre",
        thumbnail: 255,
    },
    {
        spotify: "todo: find genre links",
        id: "Punk",
        title: "Punk",
        description: "genre",
        type: "genre",
        thumbnail: 258,
    },
    {
        spotify: "todo: find genre links",
        id: "Punk-rock",
        title: "Punk-rock",
        description: "genre",
        type: "genre",
        thumbnail: 260,
    },
    {
        spotify: "todo: find genre links",
        id: "R-n-b",
        title: "R-n-b",
        description: "genre",
        type: "genre",
        thumbnail: 263,
    },
    {
        spotify: "todo: find genre links",
        id: "Rainy-day",
        title: "Rainy-day",
        description: "genre",
        type: "genre",
        thumbnail: 266,
    },
    {
        spotify: "todo: find genre links",
        id: "Reggae",
        title: "Reggae",
        description: "genre",
        type: "genre",
        thumbnail: 269,
    },
    {
        spotify: "todo: find genre links",
        id: "Reggaeton",
        title: "Reggaeton",
        description: "genre",
        type: "genre",
        thumbnail: 271,
    },
    {
        spotify: "todo: find genre links",
        id: "Road-trip",
        title: "Road-trip",
        description: "genre",
        type: "genre",
        thumbnail: 274,
    },
    {
        spotify: "todo: find genre links",
        id: "Rock",
        title: "Rock",
        description: "genre",
        type: "genre",
        thumbnail: 277,
    },
    {
        spotify: "todo: find genre links",
        id: "Rock-n-roll",
        title: "Rock-n-roll",
        description: "genre",
        type: "genre",
        thumbnail: 279,
    },
    {
        spotify: "todo: find genre links",
        id: "Rockabilly",
        title: "Rockabilly",
        description: "genre",
        type: "genre",
        thumbnail: 282,
    },
    {
        spotify: "todo: find genre links",
        id: "Romance",
        title: "Romance",
        description: "genre",
        type: "genre",
        thumbnail: 285,
    },
    {
        spotify: "todo: find genre links",
        id: "Sad",
        title: "Sad",
        description: "genre",
        type: "genre",
        thumbnail: 287,
    },
    {
        spotify: "todo: find genre links",
        id: "Salsa",
        title: "Salsa",
        description: "genre",
        type: "genre",
        thumbnail: 290,
    },
    {
        spotify: "todo: find genre links",
        id: "Samba",
        title: "Samba",
        description: "genre",
        type: "genre",
        thumbnail: 293,
    },
    {
        spotify: "todo: find genre links",
        id: "Sertanejo",
        title: "Sertanejo",
        description: "genre",
        type: "genre",
        thumbnail: 296,
    },
    {
        spotify: "todo: find genre links",
        id: "Show-tunes",
        title: "Show-tunes",
        description: "genre",
        type: "genre",
        thumbnail: 298,
    },
    {
        spotify: "todo: find genre links",
        id: "Singer-songwriter",
        title: "Singer-songwriter",
        description: "genre",
        type: "genre",
        thumbnail: 301,
    },
    {
        spotify: "todo: find genre links",
        id: "Ska",
        title: "Ska",
        description: "genre",
        type: "genre",
        thumbnail: 304,
    },
    {
        spotify: "todo: find genre links",
        id: "Sleep",
        title: "Sleep",
        description: "genre",
        type: "genre",
        thumbnail: 306,
    },
    {
        spotify: "todo: find genre links",
        id: "Songwriter",
        title: "Songwriter",
        description: "genre",
        type: "genre",
        thumbnail: 309,
    },
    {
        spotify: "todo: find genre links",
        id: "Soul",
        title: "Soul",
        description: "genre",
        type: "genre",
        thumbnail: 312,
    },
    {
        spotify: "todo: find genre links",
        id: "Soundtracks",
        title: "Soundtracks",
        description: "genre",
        type: "genre",
        thumbnail: 314,
    },
    {
        spotify: "todo: find genre links",
        id: "Spanish",
        title: "Spanish",
        description: "genre",
        type: "genre",
        thumbnail: 317,
    },
    {
        spotify: "todo: find genre links",
        id: "Study",
        title: "Study",
        description: "genre",
        type: "genre",
        thumbnail: 320,
    },
    {
        spotify: "todo: find genre links",
        id: "Summer",
        title: "Summer",
        description: "genre",
        type: "genre",
        thumbnail: 323,
    },
    {
        spotify: "todo: find genre links",
        id: "Swedish",
        title: "Swedish",
        description: "genre",
        type: "genre",
        thumbnail: 325,
    },
    {
        spotify: "todo: find genre links",
        id: "Synth-pop",
        title: "Synth-pop",
        description: "genre",
        type: "genre",
        thumbnail: 328,
    },
    {
        spotify: "todo: find genre links",
        id: "Tango",
        title: "Tango",
        description: "genre",
        type: "genre",
        thumbnail: 331,
    },
    {
        spotify: "todo: find genre links",
        id: "Techno",
        title: "Techno",
        description: "genre",
        type: "genre",
        thumbnail: 333,
    },
    {
        spotify: "todo: find genre links",
        id: "Trance",
        title: "Trance",
        description: "genre",
        type: "genre",
        thumbnail: 336,
    },
    {
        spotify: "todo: find genre links",
        id: "Trip-hop",
        title: "Trip-hop",
        description: "genre",
        type: "genre",
        thumbnail: 339,
    },
    {
        spotify: "todo: find genre links",
        id: "Turkish",
        title: "Turkish",
        description: "genre",
        type: "genre",
        thumbnail: 341,
    },
    {
        spotify: "todo: find genre links",
        id: "Work-out",
        title: "Work-out",
        description: "genre",
        type: "genre",
        thumbnail: 344,
    },
    {
        spotify: "todo: find genre links",
        id: "World-music",
        title: "World-music",
        description: "genre",
        type: "genre",
        thumbnail: 347,
    },
];

export const allRules: Rule[] = [
    {
        name: "Danceability",
        type: "range",
        value: 50,
        range: ["0", "full send"],
        description:
            "How suitable a track is for dancing based on a combination of musical elements including tempo, rhythm stability, beat strength, and overall regularity.",
    },
    {
        name: "Mood",
        type: "axis",
        value: [50, 50],
        range: [
            ["negative", "positive"],
            ["intense", "mild"],
        ],
        description:
            "Choose the Mood according to the Arousal-Valence model of emotions (Amount of Arousal and Valence of a Track).",
    },
    {
        name: "Instrumentalness",
        type: "range",
        value: 50,
        range: ["vocal", "instrumental"],
        description: "High value represents more instrumental tracks, low represents more vocals in tracks.",
    },
    {
        name: "Accousticness",
        type: "range",
        value: 50,
        range: ["synthetic", "accoustic"],
        description: "Whether the Song is accoustic or not.",
    },
    {
        name: "Liveness",
        type: "range",
        value: 50,
        range: ["studio", "live"],
        description:
            "Want to listen to live performances? Detects the presence of an audience in the recording. Higher liveness values represent an increased probability that the track was performed live. A value above 0.8 provides strong likelihood that the track is live.",
    },
    {
        name: "Popularity",
        type: "range",
        value: 50,
        range: ["underground", "mainstream"],
        description:
            "Want to filter out mainstream music? Or only listen to what others approved by listening to it? This is the right filter for you.",
    },
    {
        name: "Mode",
        type: "boolean",
        value: false,
        range: ["Minor", "Major"],
        description: "Choose between Tracks using Minor or Major mode.",
    },
    {
        name: "Tempo",
        type: "range",
        value: 100,
        range: ["40", "250"],
        description: "Choose the Tempo of the Track.",
    },
];
