import { Rule, Seed } from "@/types/spotify";

export const allGenres: string[] = [
    "acoustic",
    "afrobeat",
    "alt-rock",
    "alternative",
    "ambient",
    "anime",
    "black-metal",
    "bluegrass",
    "blues",
    "bossanova",
    "brazil",
    "breakbeat",
    "british",
    "cantopop",
    "chicago-house",
    "children",
    "chill",
    "classical",
    "club",
    "comedy",
    "country",
    "dance",
    "dancehall",
    "death-metal",
    "deep-house",
    "detroit-techno",
    "disco",
    "disney",
    "drum-and-bass",
    "dub",
    "dubstep",
    "edm",
    "electro",
    "electronic",
    "emo",
    "folk",
    "forro",
    "french",
    "funk",
    "garage",
    "german",
    "gospel",
    "goth",
    "grindcore",
    "groove",
    "grunge",
    "guitar",
    "happy",
    "hard-rock",
    "hardcore",
    "hardstyle",
    "heavy-metal",
    "hip-hop",
    "holidays",
    "honky-tonk",
    "house",
    "idm",
    "indian",
    "indie",
    "indie-pop",
    "industrial",
    "iranian",
    "j-dance",
    "j-idol",
    "j-pop",
    "j-rock",
    "jazz",
    "k-pop",
    "kids",
    "latin",
    "latino",
    "malay",
    "mandopop",
    "metal",
    "metal-misc",
    "metalcore",
    "minimal-techno",
    "movies",
    "mpb",
    "new-age",
    "new-release",
    "opera",
    "pagode",
    "party",
    "philippines-opm",
    "piano",
    "pop",
    "pop-film",
    "post-dubstep",
    "power-pop",
    "progressive-house",
    "psych-rock",
    "punk",
    "punk-rock",
    "r-n-b",
    "rainy-day",
    "reggae",
    "reggaeton",
    "road-trip",
    "rock",
    "rock-n-roll",
    "rockabilly",
    "romance",
    "sad",
    "salsa",
    "samba",
    "sertanejo",
    "show-tunes",
    "singer-songwriter",
    "ska",
    "sleep",
    "songwriter",
    "soul",
    "soundtracks",
    "spanish",
    "study",
    "summer",
    "swedish",
    "synth-pop",
    "tango",
    "techno",
    "trance",
    "trip-hop",
    "turkish",
    "work-out",
    "world-music",
];

export const allGenresSeeds: Seed[] = [
    {
        spotify: "todo: find genre links",
        id: "acoustic",
        title: "acoustic",
        description: "genre",
        type: "genre",
        thumbnail: 10,
    },
    {
        spotify: "todo: find genre links",
        id: "afrobeat",
        title: "afrobeat",
        description: "genre",
        type: "genre",
        thumbnail: 12,
    },
    {
        spotify: "todo: find genre links",
        id: "alt-rock",
        title: "alt-rock",
        description: "genre",
        type: "genre",
        thumbnail: 15,
    },
    {
        spotify: "todo: find genre links",
        id: "alternative",
        title: "alternative",
        description: "genre",
        type: "genre",
        thumbnail: 18,
    },
    {
        spotify: "todo: find genre links",
        id: "ambient",
        title: "ambient",
        description: "genre",
        type: "genre",
        thumbnail: 20,
    },
    {
        spotify: "todo: find genre links",
        id: "anime",
        title: "anime",
        description: "genre",
        type: "genre",
        thumbnail: 23,
    },
    {
        spotify: "todo: find genre links",
        id: "black-metal",
        title: "black-metal",
        description: "genre",
        type: "genre",
        thumbnail: 26,
    },
    {
        spotify: "todo: find genre links",
        id: "bluegrass",
        title: "bluegrass",
        description: "genre",
        type: "genre",
        thumbnail: 28,
    },
    {
        spotify: "todo: find genre links",
        id: "blues",
        title: "blues",
        description: "genre",
        type: "genre",
        thumbnail: 31,
    },
    {
        spotify: "todo: find genre links",
        id: "bossanova",
        title: "bossanova",
        description: "genre",
        type: "genre",
        thumbnail: 34,
    },
    {
        spotify: "todo: find genre links",
        id: "brazil",
        title: "brazil",
        description: "genre",
        type: "genre",
        thumbnail: 36,
    },
    {
        spotify: "todo: find genre links",
        id: "breakbeat",
        title: "breakbeat",
        description: "genre",
        type: "genre",
        thumbnail: 39,
    },
    {
        spotify: "todo: find genre links",
        id: "british",
        title: "british",
        description: "genre",
        type: "genre",
        thumbnail: 42,
    },
    {
        spotify: "todo: find genre links",
        id: "cantopop",
        title: "cantopop",
        description: "genre",
        type: "genre",
        thumbnail: 45,
    },
    {
        spotify: "todo: find genre links",
        id: "chicago-house",
        title: "chicago-house",
        description: "genre",
        type: "genre",
        thumbnail: 47,
    },
    {
        spotify: "todo: find genre links",
        id: "children",
        title: "children",
        description: "genre",
        type: "genre",
        thumbnail: 50,
    },
    {
        spotify: "todo: find genre links",
        id: "chill",
        title: "chill",
        description: "genre",
        type: "genre",
        thumbnail: 53,
    },
    {
        spotify: "todo: find genre links",
        id: "classical",
        title: "classical",
        description: "genre",
        type: "genre",
        thumbnail: 55,
    },
    {
        spotify: "todo: find genre links",
        id: "club",
        title: "club",
        description: "genre",
        type: "genre",
        thumbnail: 58,
    },
    {
        spotify: "todo: find genre links",
        id: "comedy",
        title: "comedy",
        description: "genre",
        type: "genre",
        thumbnail: 61,
    },
    {
        spotify: "todo: find genre links",
        id: "country",
        title: "country",
        description: "genre",
        type: "genre",
        thumbnail: 63,
    },
    {
        spotify: "todo: find genre links",
        id: "dance",
        title: "dance",
        description: "genre",
        type: "genre",
        thumbnail: 66,
    },
    {
        spotify: "todo: find genre links",
        id: "dancehall",
        title: "dancehall",
        description: "genre",
        type: "genre",
        thumbnail: 69,
    },
    {
        spotify: "todo: find genre links",
        id: "death-metal",
        title: "death-metal",
        description: "genre",
        type: "genre",
        thumbnail: 72,
    },
    {
        spotify: "todo: find genre links",
        id: "deep-house",
        title: "deep-house",
        description: "genre",
        type: "genre",
        thumbnail: 74,
    },
    {
        spotify: "todo: find genre links",
        id: "detroit-techno",
        title: "detroit-techno",
        description: "genre",
        type: "genre",
        thumbnail: 77,
    },
    {
        spotify: "todo: find genre links",
        id: "disco",
        title: "disco",
        description: "genre",
        type: "genre",
        thumbnail: 80,
    },
    {
        spotify: "todo: find genre links",
        id: "disney",
        title: "disney",
        description: "genre",
        type: "genre",
        thumbnail: 82,
    },
    {
        spotify: "todo: find genre links",
        id: "drum-and-bass",
        title: "drum-and-bass",
        description: "genre",
        type: "genre",
        thumbnail: 85,
    },
    {
        spotify: "todo: find genre links",
        id: "dub",
        title: "dub",
        description: "genre",
        type: "genre",
        thumbnail: 88,
    },
    {
        spotify: "todo: find genre links",
        id: "dubstep",
        title: "dubstep",
        description: "genre",
        type: "genre",
        thumbnail: 90,
    },
    {
        spotify: "todo: find genre links",
        id: "edm",
        title: "edm",
        description: "genre",
        type: "genre",
        thumbnail: 93,
    },
    {
        spotify: "todo: find genre links",
        id: "electro",
        title: "electro",
        description: "genre",
        type: "genre",
        thumbnail: 96,
    },
    {
        spotify: "todo: find genre links",
        id: "electronic",
        title: "electronic",
        description: "genre",
        type: "genre",
        thumbnail: 99,
    },
    {
        spotify: "todo: find genre links",
        id: "emo",
        title: "emo",
        description: "genre",
        type: "genre",
        thumbnail: 101,
    },
    {
        spotify: "todo: find genre links",
        id: "folk",
        title: "folk",
        description: "genre",
        type: "genre",
        thumbnail: 104,
    },
    {
        spotify: "todo: find genre links",
        id: "forro",
        title: "forro",
        description: "genre",
        type: "genre",
        thumbnail: 107,
    },
    {
        spotify: "todo: find genre links",
        id: "french",
        title: "french",
        description: "genre",
        type: "genre",
        thumbnail: 109,
    },
    {
        spotify: "todo: find genre links",
        id: "funk",
        title: "funk",
        description: "genre",
        type: "genre",
        thumbnail: 112,
    },
    {
        spotify: "todo: find genre links",
        id: "garage",
        title: "garage",
        description: "genre",
        type: "genre",
        thumbnail: 115,
    },
    {
        spotify: "todo: find genre links",
        id: "german",
        title: "german",
        description: "genre",
        type: "genre",
        thumbnail: 117,
    },
    {
        spotify: "todo: find genre links",
        id: "gospel",
        title: "gospel",
        description: "genre",
        type: "genre",
        thumbnail: 120,
    },
    {
        spotify: "todo: find genre links",
        id: "goth",
        title: "goth",
        description: "genre",
        type: "genre",
        thumbnail: 123,
    },
    {
        spotify: "todo: find genre links",
        id: "grindcore",
        title: "grindcore",
        description: "genre",
        type: "genre",
        thumbnail: 126,
    },
    {
        spotify: "todo: find genre links",
        id: "groove",
        title: "groove",
        description: "genre",
        type: "genre",
        thumbnail: 128,
    },
    {
        spotify: "todo: find genre links",
        id: "grunge",
        title: "grunge",
        description: "genre",
        type: "genre",
        thumbnail: 131,
    },
    {
        spotify: "todo: find genre links",
        id: "guitar",
        title: "guitar",
        description: "genre",
        type: "genre",
        thumbnail: 134,
    },
    {
        spotify: "todo: find genre links",
        id: "happy",
        title: "happy",
        description: "genre",
        type: "genre",
        thumbnail: 136,
    },
    {
        spotify: "todo: find genre links",
        id: "hard-rock",
        title: "hard-rock",
        description: "genre",
        type: "genre",
        thumbnail: 139,
    },
    {
        spotify: "todo: find genre links",
        id: "hardcore",
        title: "hardcore",
        description: "genre",
        type: "genre",
        thumbnail: 142,
    },
    {
        spotify: "todo: find genre links",
        id: "hardstyle",
        title: "hardstyle",
        description: "genre",
        type: "genre",
        thumbnail: 144,
    },
    {
        spotify: "todo: find genre links",
        id: "heavy-metal",
        title: "heavy-metal",
        description: "genre",
        type: "genre",
        thumbnail: 147,
    },
    {
        spotify: "todo: find genre links",
        id: "hip-hop",
        title: "hip-hop",
        description: "genre",
        type: "genre",
        thumbnail: 150,
    },
    {
        spotify: "todo: find genre links",
        id: "holidays",
        title: "holidays",
        description: "genre",
        type: "genre",
        thumbnail: 153,
    },
    {
        spotify: "todo: find genre links",
        id: "honky-tonk",
        title: "honky-tonk",
        description: "genre",
        type: "genre",
        thumbnail: 155,
    },
    {
        spotify: "todo: find genre links",
        id: "house",
        title: "house",
        description: "genre",
        type: "genre",
        thumbnail: 158,
    },
    {
        spotify: "todo: find genre links",
        id: "idm",
        title: "idm",
        description: "genre",
        type: "genre",
        thumbnail: 161,
    },
    {
        spotify: "todo: find genre links",
        id: "indian",
        title: "indian",
        description: "genre",
        type: "genre",
        thumbnail: 163,
    },
    {
        spotify: "todo: find genre links",
        id: "indie",
        title: "indie",
        description: "genre",
        type: "genre",
        thumbnail: 166,
    },
    {
        spotify: "todo: find genre links",
        id: "indie-pop",
        title: "indie-pop",
        description: "genre",
        type: "genre",
        thumbnail: 169,
    },
    {
        spotify: "todo: find genre links",
        id: "industrial",
        title: "industrial",
        description: "genre",
        type: "genre",
        thumbnail: 171,
    },
    {
        spotify: "todo: find genre links",
        id: "iranian",
        title: "iranian",
        description: "genre",
        type: "genre",
        thumbnail: 174,
    },
    {
        spotify: "todo: find genre links",
        id: "j-dance",
        title: "j-dance",
        description: "genre",
        type: "genre",
        thumbnail: 177,
    },
    {
        spotify: "todo: find genre links",
        id: "j-idol",
        title: "j-idol",
        description: "genre",
        type: "genre",
        thumbnail: 180,
    },
    {
        spotify: "todo: find genre links",
        id: "j-pop",
        title: "j-pop",
        description: "genre",
        type: "genre",
        thumbnail: 182,
    },
    {
        spotify: "todo: find genre links",
        id: "j-rock",
        title: "j-rock",
        description: "genre",
        type: "genre",
        thumbnail: 185,
    },
    {
        spotify: "todo: find genre links",
        id: "jazz",
        title: "jazz",
        description: "genre",
        type: "genre",
        thumbnail: 188,
    },
    {
        spotify: "todo: find genre links",
        id: "k-pop",
        title: "k-pop",
        description: "genre",
        type: "genre",
        thumbnail: 190,
    },
    {
        spotify: "todo: find genre links",
        id: "kids",
        title: "kids",
        description: "genre",
        type: "genre",
        thumbnail: 193,
    },
    {
        spotify: "todo: find genre links",
        id: "latin",
        title: "latin",
        description: "genre",
        type: "genre",
        thumbnail: 196,
    },
    {
        spotify: "todo: find genre links",
        id: "latino",
        title: "latino",
        description: "genre",
        type: "genre",
        thumbnail: 198,
    },
    {
        spotify: "todo: find genre links",
        id: "malay",
        title: "malay",
        description: "genre",
        type: "genre",
        thumbnail: 201,
    },
    {
        spotify: "todo: find genre links",
        id: "mandopop",
        title: "mandopop",
        description: "genre",
        type: "genre",
        thumbnail: 204,
    },
    {
        spotify: "todo: find genre links",
        id: "metal",
        title: "metal",
        description: "genre",
        type: "genre",
        thumbnail: 206,
    },
    {
        spotify: "todo: find genre links",
        id: "metal-misc",
        title: "metal-misc",
        description: "genre",
        type: "genre",
        thumbnail: 209,
    },
    {
        spotify: "todo: find genre links",
        id: "metalcore",
        title: "metalcore",
        description: "genre",
        type: "genre",
        thumbnail: 212,
    },
    {
        spotify: "todo: find genre links",
        id: "minimal-techno",
        title: "minimal-techno",
        description: "genre",
        type: "genre",
        thumbnail: 215,
    },
    {
        spotify: "todo: find genre links",
        id: "movies",
        title: "movies",
        description: "genre",
        type: "genre",
        thumbnail: 217,
    },
    {
        spotify: "todo: find genre links",
        id: "mpb",
        title: "mpb",
        description: "genre",
        type: "genre",
        thumbnail: 220,
    },
    {
        spotify: "todo: find genre links",
        id: "new-age",
        title: "new-age",
        description: "genre",
        type: "genre",
        thumbnail: 223,
    },
    {
        spotify: "todo: find genre links",
        id: "new-release",
        title: "new-release",
        description: "genre",
        type: "genre",
        thumbnail: 225,
    },
    {
        spotify: "todo: find genre links",
        id: "opera",
        title: "opera",
        description: "genre",
        type: "genre",
        thumbnail: 228,
    },
    {
        spotify: "todo: find genre links",
        id: "pagode",
        title: "pagode",
        description: "genre",
        type: "genre",
        thumbnail: 231,
    },
    {
        spotify: "todo: find genre links",
        id: "party",
        title: "party",
        description: "genre",
        type: "genre",
        thumbnail: 233,
    },
    {
        spotify: "todo: find genre links",
        id: "philippines-opm",
        title: "philippines-opm",
        description: "genre",
        type: "genre",
        thumbnail: 236,
    },
    {
        spotify: "todo: find genre links",
        id: "piano",
        title: "piano",
        description: "genre",
        type: "genre",
        thumbnail: 239,
    },
    {
        spotify: "todo: find genre links",
        id: "pop",
        title: "pop",
        description: "genre",
        type: "genre",
        thumbnail: 242,
    },
    {
        spotify: "todo: find genre links",
        id: "pop-film",
        title: "pop-film",
        description: "genre",
        type: "genre",
        thumbnail: 244,
    },
    {
        spotify: "todo: find genre links",
        id: "post-dubstep",
        title: "post-dubstep",
        description: "genre",
        type: "genre",
        thumbnail: 247,
    },
    {
        spotify: "todo: find genre links",
        id: "power-pop",
        title: "power-pop",
        description: "genre",
        type: "genre",
        thumbnail: 250,
    },
    {
        spotify: "todo: find genre links",
        id: "progressive-house",
        title: "progressive-house",
        description: "genre",
        type: "genre",
        thumbnail: 252,
    },
    {
        spotify: "todo: find genre links",
        id: "psych-rock",
        title: "psych-rock",
        description: "genre",
        type: "genre",
        thumbnail: 255,
    },
    {
        spotify: "todo: find genre links",
        id: "punk",
        title: "punk",
        description: "genre",
        type: "genre",
        thumbnail: 258,
    },
    {
        spotify: "todo: find genre links",
        id: "punk-rock",
        title: "punk-rock",
        description: "genre",
        type: "genre",
        thumbnail: 260,
    },
    {
        spotify: "todo: find genre links",
        id: "r-n-b",
        title: "r-n-b",
        description: "genre",
        type: "genre",
        thumbnail: 263,
    },
    {
        spotify: "todo: find genre links",
        id: "rainy-day",
        title: "rainy-day",
        description: "genre",
        type: "genre",
        thumbnail: 266,
    },
    {
        spotify: "todo: find genre links",
        id: "reggae",
        title: "reggae",
        description: "genre",
        type: "genre",
        thumbnail: 269,
    },
    {
        spotify: "todo: find genre links",
        id: "reggaeton",
        title: "reggaeton",
        description: "genre",
        type: "genre",
        thumbnail: 271,
    },
    {
        spotify: "todo: find genre links",
        id: "road-trip",
        title: "road-trip",
        description: "genre",
        type: "genre",
        thumbnail: 274,
    },
    {
        spotify: "todo: find genre links",
        id: "rock",
        title: "rock",
        description: "genre",
        type: "genre",
        thumbnail: 277,
    },
    {
        spotify: "todo: find genre links",
        id: "rock-n-roll",
        title: "rock-n-roll",
        description: "genre",
        type: "genre",
        thumbnail: 279,
    },
    {
        spotify: "todo: find genre links",
        id: "rockabilly",
        title: "rockabilly",
        description: "genre",
        type: "genre",
        thumbnail: 282,
    },
    {
        spotify: "todo: find genre links",
        id: "romance",
        title: "romance",
        description: "genre",
        type: "genre",
        thumbnail: 285,
    },
    {
        spotify: "todo: find genre links",
        id: "sad",
        title: "sad",
        description: "genre",
        type: "genre",
        thumbnail: 287,
    },
    {
        spotify: "todo: find genre links",
        id: "salsa",
        title: "salsa",
        description: "genre",
        type: "genre",
        thumbnail: 290,
    },
    {
        spotify: "todo: find genre links",
        id: "samba",
        title: "samba",
        description: "genre",
        type: "genre",
        thumbnail: 293,
    },
    {
        spotify: "todo: find genre links",
        id: "sertanejo",
        title: "sertanejo",
        description: "genre",
        type: "genre",
        thumbnail: 296,
    },
    {
        spotify: "todo: find genre links",
        id: "show-tunes",
        title: "show-tunes",
        description: "genre",
        type: "genre",
        thumbnail: 298,
    },
    {
        spotify: "todo: find genre links",
        id: "singer-songwriter",
        title: "singer-songwriter",
        description: "genre",
        type: "genre",
        thumbnail: 301,
    },
    {
        spotify: "todo: find genre links",
        id: "ska",
        title: "ska",
        description: "genre",
        type: "genre",
        thumbnail: 304,
    },
    {
        spotify: "todo: find genre links",
        id: "sleep",
        title: "sleep",
        description: "genre",
        type: "genre",
        thumbnail: 306,
    },
    {
        spotify: "todo: find genre links",
        id: "songwriter",
        title: "songwriter",
        description: "genre",
        type: "genre",
        thumbnail: 309,
    },
    {
        spotify: "todo: find genre links",
        id: "soul",
        title: "soul",
        description: "genre",
        type: "genre",
        thumbnail: 312,
    },
    {
        spotify: "todo: find genre links",
        id: "soundtracks",
        title: "soundtracks",
        description: "genre",
        type: "genre",
        thumbnail: 314,
    },
    {
        spotify: "todo: find genre links",
        id: "spanish",
        title: "spanish",
        description: "genre",
        type: "genre",
        thumbnail: 317,
    },
    {
        spotify: "todo: find genre links",
        id: "study",
        title: "study",
        description: "genre",
        type: "genre",
        thumbnail: 320,
    },
    {
        spotify: "todo: find genre links",
        id: "summer",
        title: "summer",
        description: "genre",
        type: "genre",
        thumbnail: 323,
    },
    {
        spotify: "todo: find genre links",
        id: "swedish",
        title: "swedish",
        description: "genre",
        type: "genre",
        thumbnail: 325,
    },
    {
        spotify: "todo: find genre links",
        id: "synth-pop",
        title: "synth-pop",
        description: "genre",
        type: "genre",
        thumbnail: 328,
    },
    {
        spotify: "todo: find genre links",
        id: "tango",
        title: "tango",
        description: "genre",
        type: "genre",
        thumbnail: 331,
    },
    {
        spotify: "todo: find genre links",
        id: "techno",
        title: "techno",
        description: "genre",
        type: "genre",
        thumbnail: 333,
    },
    {
        spotify: "todo: find genre links",
        id: "trance",
        title: "trance",
        description: "genre",
        type: "genre",
        thumbnail: 336,
    },
    {
        spotify: "todo: find genre links",
        id: "trip-hop",
        title: "trip-hop",
        description: "genre",
        type: "genre",
        thumbnail: 339,
    },
    {
        spotify: "todo: find genre links",
        id: "turkish",
        title: "turkish",
        description: "genre",
        type: "genre",
        thumbnail: 341,
    },
    {
        spotify: "todo: find genre links",
        id: "work-out",
        title: "work-out",
        description: "genre",
        type: "genre",
        thumbnail: 344,
    },
    {
        spotify: "todo: find genre links",
        id: "world-music",
        title: "world-music",
        description: "genre",
        type: "genre",
        thumbnail: 347,
    },
];

export const allRules: Rule[] = [
    {
        name: "Danceability",
        type: "range",
        value: 50,
        range: ["Not Dancable", "Danceable"],
        description:
            "How suitable a track is for dancing based on a combination of musical elements including tempo, rhythm stability, beat strength, and overall regularity.",
    },
    {
        name: "Mood",
        type: "axis",
        value: [50, 50],
        range: [
            ["negative", "positive"],
            ["intense", "mild"],
        ],
        description:
            "Choose the Mood according to the Arousal-Valence model of emotions (Amount of Arousal and Valence of a Track).",
    },
    {
        name: "Instrumentalness",
        type: "range",
        value: 50,
        range: ["Vocal", "Instrumental"],
        description:
            "High value represents more instrumental tracks, low represents more vocals in tracks.",
    },
    {
        name: "Accousticness",
        type: "range",
        value: 50,
        range: ["Synthetic", "Accoustic"],
        description: "Whether the Song is accoustic or not.",
    },
    {
        name: "Liveness",
        type: "range",
        value: 50,
        range: ["Studio", "Live"],
        description:
            "Want to listen to live performances? Detects the presence of an audience in the recording. Higher liveness values represent an increased probability that the track was performed live. A value above 0.8 provides strong likelihood that the track is live.",
    },
    {
        name: "Popularity",
        type: "range",
        value: 50,
        range: ["Underground", "Mainstream"],
        description:
            "Want to filter out mainstream music? Or only listen to what others approved by listening to it? This is the right filter for you.",
    },
    {
        name: "Mode",
        type: "boolean",
        value: false,
        range: ["Minor", "Major"],
        description: "Choose between Tracks using Minor or Major mode.",
    },
    {
        name: "Tempo",
        type: "range",
        value: 100,
        range: ["40", "200"],
        description: "Choose the Tempo of the Track.",
    },
];
