export const exampleUser = {
    name: "karate_morris",
    spotify_id: "karate_morris",
    playlists: [
        {
            playlist_id: "7uLe3v6V73qCNZl3oH8tgL",
            lastUpdated: new Date(1731174997564),
            preferences: {
                name: "Developing Flow",
                frequency: "weekly",
                amount: 50,
                on: 0,
            },
            seeds: [
                {
                    id: "60eKTJqG7nupTaQXthGRUG",
                    type: "track",
                    title: "Do The Deal",
                    description: "Baron Von Trax",
                    thumbnail: "https://i.scdn.co/image/ab67616d00001e02dd684bb23bf071f7f4c811a8",
                },
                {
                    id: "62lP69o3SgCbeQSJxY3XBC",
                    type: "track",
                    title: "Fenz",
                    description: "Rill",
                    thumbnail: "https://i.scdn.co/image/ab67616d00001e0218e0f1a4c740a7b146ca1e35",
                },
            ],
            rules: [
                { name: "Instrumentalness", value: 72 },
                { name: "Mood", value: [85.3216338575932, 27.083333333333332] },
            ],
            trackHistory: [
                {
                    tracks: [
                        "0EWwgvtpouV6PymQr1IIxD",
                        "3e14ePHx0Rf0BN2e81fCL9",
                        "70ErfY25BghrrGTbGo9dIl",
                        "7qp2NFrzqmarNPDK6YvMMI",
                        "70CEwRpdd5HroRPziJq89l",
                        "5QIKIx4ITPV9ieVtNT176I",
                        "6d6UBbfakwgmf6pG68Zv1u",
                        "5sFtAVm67cwzRYphYT4ZmQ",
                        "1AtqXmRHjdgIyE4Nn6uqHC",
                        "2aFYaWhuxJzAIFYgb5XU7B",
                        "5UqSSOTe2a5yDN2PucVvkZ",
                        "0kEVzlnbHHGKtAL5nP9eOb",
                        "1v5x2NkYiWpfgNj9kYrzvB",
                        "69xbwuKnxSnZvFjhoZUvcF",
                        "6GU4XA3Ux1quOYG3knqr2k",
                        "0M81RtuKqtl2xFkxxiujql",
                        "6MzORCyp8Pv3iM5fGFw8oP",
                        "1tC6SgNY7Q9eahTxSkz5fV",
                        "2VtMaXQqRcJsgLY83QCsf5",
                        "3kYLMSQlo2f8rTWKxvSadP",
                        "0QsjTEIZJbTBpaE39VqfFh",
                        "3rXcjlOc141XP7OYGEE2pF",
                        "2bpSFLiUIpIIduAP9iysWr",
                        "53iCpRBnZqy9ZtAhstsNB0",
                        "67CbgvWOaukj3CKqD3Tfkv",
                        "0CvRPlXsF7RUbXG5HutxHR",
                        "4QphCIeDd9wsj6wwDYAdWD",
                        "2riBrhwgDBZCGNVSteY7S5",
                        "1rRuFCXtpDxjFypUgX4jFn",
                        "2Sd0BmlBeiCFqKWqMR24Eu",
                        "1KKy0A0bc2kbmX5FReztY5",
                        "2EWzIpbg2ouYF9sJrBwx8D",
                        "3Lu3lWMOm7ev8DoT8cePmA",
                        "4leSDpVLhQ0p4vLYmRVFP5",
                        "2QnWMlj2f8aNlzeZfcbQbr",
                        "0JCfG8nDSO30YY5kLnOH5i",
                        "5wNTkfvA1uTNY7OYziddOb",
                        "4H7IKL8lbBNUEpQXc8Gbj5",
                        "2aE5cguTGMhqdPHSfaPiAw",
                        "6YJeU7lACkABRbSERg1W8b",
                        "0JsfPGaK3Nb6P0S2fVTvvx",
                        "26OASDS54G0ot55BztyMJf",
                        "3OSd7D93oTu5ofNolYV91V",
                        "17PxRve6HMubrjkioWYqCd",
                        "3zSYukXNdD83wXUJxEyQWF",
                        "57Uw50XxGDd9R3ODYnI8am",
                        "32rwzhal6wnk6SKYL5lCWK",
                        "3oNYTAG76QCwEYiKrywhZW",
                        "4HjK2goaih97Gqmk1oHbLp",
                        "2fDW4PPvuSWK0XWcwDGgiW",
                    ],
                    added_at: null,
                },
                {
                    tracks: [
                        "4kpx4wMn5AGVY5gVN3XbB8",
                        "1qFaSs96rTiEBWE6UMXlCQ",
                        "7oHdGobTs66dcu7lA4TEWd",
                        "1rwRiGxvDbgTfFr6pDeoOV",
                        "5fbmbHy4g0p2Hu4CnrpHmK",
                        "5ix8OYFmbkHzDcYfX8tT95",
                        "4vO1QjxASB0bjVdIvsp86V",
                        "7kBYPyaxF3oE9EgjOMpGKs",
                        "3LjOH3FVC52zaCldCnx4Gg",
                        "0tzl0pDWyZCek5SHB58xql",
                        "4J80B3tZUxgPB3bp2Pvc9b",
                        "6RPjcPLgM6VKb7p4BfZJDs",
                        "6JDtgUuaDkxQ8kB1sVSjBZ",
                        "0YuMBmKI7n6EavxT7VAwI6",
                        "0xyFqLGqzQWuzvan1ASbdv",
                        "3qkCJ3Zw1I6c3xPjAXQz7b",
                        "5eF2fmkCbybtS17Sp9Zpbj",
                        "4fmMlfYmxRNdTEWXBJyaZa",
                        "1DBq8StBci7VwOktDYjUfP",
                        "4hWBHDSaXuIpO3ueB9VxKW",
                        "3KtDSBXSivVNFKBa6bFmeP",
                        "1IpVDYBraOYeAUM73Lm7NZ",
                        "6r9ECcAwAtEmFx7vhQ7x0R",
                        "0q75kLhyMDwne5HlyCb17q",
                        "7imXx79izpmftzHyFchxdV",
                        "1TBPwNSJpasJnHHRBDG3gE",
                        "3u6du2zzwtCbDXhAFQSYan",
                        "2UT1A00dLirSi2eFKuSIcq",
                        "4b0NUoSxOiFniSPGvy7bRT",
                        "5mJbLz0hl8LIagj8d22FX9",
                        "6pjgwodq0dUiVuI7TS6jue",
                        "3T510ANYRCF5FyvuEeT7NU",
                        "4efJTFW6jZcvbLdJ1x5Uaj",
                        "1fAeBD7StKvaRWyBgUK8vw",
                        "2SjTV5tVKofYLnAz4xIwGr",
                        "3zyTgrkhbkC4Aepc4SyjGX",
                        "1BpPAxMHr3tWgbVmrgwjkt",
                        "78wWMyvjAGsUnyeY6rl9tR",
                        "1o4SNbvOJpBVwEXnRlBaGa",
                        "4eCVdos2DA6AcC5asD1nWA",
                        "2ax3w0bz3RxGseSyAXf5ni",
                        "5lTJ4wq22sPEQnAkSKSoab",
                        "7wUfvWKAPZRoaMDASFgO91",
                        "71HTa9ZGY9mU39zoygwrLt",
                        "0yChtXqne3x3YDFVxqWHpK",
                        "1KjwoccTB7wHHhtVmPNjpN",
                        "3noXjXNFh4stDpDKqduGEY",
                        "1ga78K7Bj4zvXN7vXPGG6X",
                        "0IcVYaJEw22n1d4xZia5nI",
                        "3Dp1AaJPY94aovUxE4IidD",
                    ],
                    added_at: null,
                },
                {
                    tracks: [
                        "3IC5oKi7Fo7OLJlYj3fSOp",
                        "1Rq3Yz9pFEpQbYyjZ8yuKT",
                        "4K4Q21TSr31xxEHKoKQQPA",
                        "1qyns5MRU7J7mkAgUkTtEY",
                        "18foj3KoiCQSEyXzOyy0kh",
                        "51sh8Q7VYcknNufSo97UVF",
                        "1XQNOZS49KxbIGFsDJZ57Q",
                        "0u5gsyOFhJVh4mJCoO0p6T",
                        "1EA7LpHzcJ3kGtsGo66FdE",
                        "4CH9G8YVkKukHd2pDXUOS0",
                        "7BuWqLA9Gr943DKFUwyrKE",
                        "4oQnQewIq7SsVb6U3voVYg",
                        "6HdYRgFPNPsQETMAp9IEF6",
                        "2PjO8YJ9haoJAJPuP9rwAS",
                        "0GKIXL6LAv7vKUc4pYOBaM",
                        "5TgR0sy5I9sWS0jZ7pGTGS",
                        "5977V7OhTUTwe1Dn439Qz8",
                        "4b7QaEY0g9cH1w87wMlo86",
                        "26ZCGaiUZKmN9aWJTBiFkH",
                        "6QwoQQLc9JoWz7XK7jymzQ",
                        "7Gmq9uNMrZoB3QamiIm4zT",
                        "3MZqUh4GVaA1RTvg8IapOj",
                        "3tg2s9xIwtFS4ULvlz4gtg",
                        "0wm3JfMMCFXVC8U0JqvSvt",
                        "6YxqrwVQamLm3029qHtByh",
                        "0Wd754HFjUPXozX3B2yRyf",
                        "2MR4BqIUtoBLWuZDVlZDQz",
                        "7AeN1ihkjZeNE2XiCL5YQI",
                        "5Me1jDe6aXU7xIr2m4WBEa",
                        "3METanqjj23WcjlVPLtSMw",
                        "44rOMa7eHxiQFw56g56K2E",
                        "3r9BWWxWS1omkF5kpGOBJp",
                        "0uI03laqgrKGGIczz3ndMA",
                        "1TjyIHkELTzdtgZgytUMId",
                        "1vVp0ydhd4HSzWfQQutwSR",
                        "0fc7Lq7G2ezTxX31iTG0S5",
                        "05tuGow7Jh7szxV1jZi7id",
                        "7Am8CJvEdFVORYjaJpKY76",
                        "0QAvdYf88PSCbd5dHIOdcs",
                        "2JHcmY4JKfjnsc0BSaWShb",
                        "25rwbYtFKt5NLJouwObxu7",
                        "1ce82XLJP9RbCCzlug0g7A",
                        "1TIixJZfdH3YaaivuSevKc",
                        "5AddVM8KMTAPoIzrgFF5mc",
                        "6BAXywn7SwAV4QlYbS9fFF",
                        "2SweUwDKRlXeCDyaJddhWJ",
                        "6uvcFhpfRLKrT4pNHueLQN",
                        "0CfUpUpO7JNfLqExighSwx",
                        "39JofJHEtg8I4fSyo7Imft",
                        "6PslLP8aOsBre5vzdXKEQr",
                    ],
                    added_at: null,
                },
            ],
            historyToRestore: 2,
        },
        {
            playlist_id: "2GIakAAlhKGNBBjAYfyxsq",
            lastUpdated: new Date(1732572901804),
            preferences: {
                name: "CozyRhythms",
                frequency: "daily",
                amount: 30,
                on: 0,
            },
            seeds: [
                {
                    id: "3J2WUEn6oFN8eDPZov7w9I",
                    type: "track",
                    title: "deep in it",
                    description: "berlioz, Ted Jasper",
                    thumbnail: "https://i.scdn.co/image/ab67616d00001e02c743cb5d8de54b825b0b3729",
                },
                {
                    id: "3f8oni9pDbNx9OM9Zx3jwJ",
                    type: "track",
                    title: "Birth",
                    description: "Floating Points",
                    thumbnail: "https://i.scdn.co/image/ab67616d00001e02d03dff7f5eeee485e5a45f62",
                },
                {
                    id: "7B0ofCHeQu2FoX7P28ZaPp",
                    type: "track",
                    title: "My Friend the Forest",
                    description: "Nils Frahm",
                    thumbnail: "https://i.scdn.co/image/ab67616d00001e02d1474ac08537f5d9655552f2",
                },
            ],
            rules: [
                { name: "Tempo", value: 80 },
                { name: "Instrumentalness", value: 100 },
                {
                    name: "Mood",
                    value: [18.640350877192983, 48.717948717948715],
                },
            ],
            trackHistory: [
                {
                    tracks: [
                        "5rAFvAvhh0HJbFDm40xFlR",
                        "2gKuOZoUGk56md4lgf9eq9",
                        "2hZ54Y3yFwPXtrqh0D2TOD",
                        "4HNb3OWOv70aNdKbfDi8BY",
                        "75IQVo8hqI1iwVZyvkN2VT",
                        "6OQTJ7llyUiejKFxR4MUuy",
                        "1NsJVeB2N76OBmCtruRLS4",
                        "37lUeF8Ced9pmr2bOqVCXV",
                        "4yFdmRQKvnqEviGXzEi9w0",
                        "58G0ljV83bdETzG02q8Wqm",
                        "7La97xgZK0kCL8jQRxCUaa",
                        "4vsCZnY7P8ccugYcCx6j7d",
                        "2v7yI88iezgRO9ka5gtUF1",
                        "6KVdlYwNuuN4catKPYj8CD",
                        "2Ep2edFgOS45QRh57Xvxvn",
                        "2uMqG8w8oi09fB2YA2QLOm",
                        "3rkesmzecZXrKZ7HA68OKZ",
                        "59tWS5kBcZ1vXL0kRhDY7z",
                        "71TGN1QCZ7r35ZRB0dBMto",
                        "5iOpT9o6X7YcKAlo1FGXXj",
                        "7p4PfzeVQpF0g0EnNuc7HT",
                        "16IplUCqMOyEaV4MeEdqPs",
                        "5cN363iH9eS8b7HxzBNJr4",
                        "4HQ2Xd0Ao8h3YKhAXYjEuZ",
                        "25sURbgUOhBWQVF1fk1j9C",
                        "6af11CfU8mPKHz0h8Eu2mP",
                        "0zJDA3RiL51315utfgY7nl",
                        "28xG0VPehoGHKE2LM6Q8lo",
                        "39Vos5uYUVso6Z03si1eNu",
                        "1OiCLJifj1jPLj5tH6tAYG",
                        "5FrBo4LSdrGEiK3HrZhVeJ",
                        "70nN851mBa1ntP1pjo3RjL",
                        "3xsBGMTDrt7Qfxf1VTiqdH",
                        "4iyH37AHAkYK1MVhveeqcm",
                        "42KQSslTRPg6B1oppAfYWR",
                        "5dGnUhahXNOOhaPk78h6sc",
                        "6sti1pkWD7vpVCDH7OZfD3",
                        "4rrNbvc5idRjJc2D2sm0wl",
                        "0opGB7qbGoEtwrlDQpa3R7",
                        "4pd0I5UlznqLhEKYDbpqPi",
                        "6G6M4fl2I0eqEQnzyTwR8m",
                        "4ordXrNPoT2614D8YaHYnC",
                        "1aboeWJVdyB1mE5sZ0kv3T",
                        "2ZYEcBXdxApveq7Xp9DPjQ",
                        "7rFu5IhLj50r2tNM2d2cat",
                        "5ksSzUpY892Gga1BlDN9ey",
                        "3yFnoUHlZhekoGsFsMFDqN",
                        "71dfXu1LwSqdzSDKGn9Fzp",
                        "5zWd3igj3YbzlrWPLMzgqZ",
                        "0qZItwF1HNXBno45TrdBSS",
                    ],
                    added_at: null,
                },
                {
                    tracks: [
                        "5G751iHQ39zBn2YJUlN7Yl",
                        "2oRJS3visA5i3TNnGdqgIl",
                        "2QHFSR7VUZZfRRwZycKqSa",
                        "3RSViRFX1LwGMrsv0NcQk4",
                        "0f2KJsmQBKOGFjKVkcSlUt",
                        "7znjbX9XdoQayIrVNdd50Z",
                        "7qOlBqDL51FLOe76CWSOqF",
                        "3JeDm203MFpRlzSFaoNEv2",
                        "76bqpXdcQBtnQw6ByKQjvO",
                        "0k4S45ArmnTtZrQZTcugpo",
                        "1Eun7gXatGlg47vgPQkXk6",
                        "69NxqbohoGAFfak85ePzzd",
                        "3ZVSzHZwoRytfFBgn6KV0K",
                        "220ZfJj309AIx2dUXJ2JoW",
                        "3VtJvlag3A95ODMu0Jmyqi",
                        "4TV3fpMUu9GD8HUwI1r5UN",
                        "0mZpVZRhcTWJXa6TQQPjNV",
                        "0Fuw8EgLFVvuhVFerLUIG8",
                        "4dQmO0TSFuCdmsdkFtZigJ",
                        "7mMqsuqwo3kSSb4GGdLGLf",
                        "5dkTYipKYiinF1Ys79cKF0",
                        "2vPBOHz2FY72u0QnRwp1NZ",
                        "0LuErgDEIHneuqo4WmLV3V",
                        "3mGMrS5Q75hP83j2xsOXOa",
                        "2B5eaSnPdUlCyN3DFbscVe",
                        "5jyhayj8H2L3OFdVzwUOx6",
                        "0eVP92az703ABJ5RxwGLeL",
                        "0511mUDvvoMoQGhdXBCFeb",
                        "33Naa5fGdmmW1Zsu8xpYx4",
                        "3DZShPBwoWAfFgPKBUcFFJ",
                        "1YQWosTIljIvxAgHWTp7KP",
                        "47KnwZdHgZJl0U2rDvMbzy",
                        "3yNUKg1GGILwCruN6U55Z4",
                        "5ZKwjf3IFCg7vWt6BDrsy6",
                        "6VezKY2wgBD7zRxWijOmmk",
                        "0WgAYN5amEwE0EE4DHyo7f",
                        "0822DXpIsja1v3Yt8sP82f",
                        "3Ff9jwYpH6x85gRVuj2ymX",
                        "13KBe7oQwRrgHePVBFgMra",
                        "48ieq4orqgVGclzC5dEMy3",
                        "7mEAEyZRuxe0jsc4trzh62",
                        "26FNSfW0PsSQKbx2sefKWq",
                        "7t6K8r0liPKbGYTEB7xru2",
                        "6lAsz2ai52QsfWX4f4PlqH",
                        "3U8DW25FSajJzQXgApAJ0B",
                        "7A4qHSH9KaFVWtdYthH2HO",
                        "5YkShqb7dH77LvxDhRTeE8",
                        "5wDyH8jsJYgqmmvanjG39y",
                        "1tnexZBkX24zkjm2s11E8Y",
                        "13soDJHFYHF1XhdWqhzpjY",
                    ],
                    added_at: null,
                },
            ],
            historyToRestore: 1,
        },
        {
            playlist_id: "0mgjCWXQJQ6yY8h4Ff72jG",
            lastUpdated: new Date(1732572902627),
            preferences: {
                name: "Shower Party",
                frequency: "daily",
                amount: 5,
                on: 0,
            },
            seeds: [
                {
                    id: "60eKTJqG7nupTaQXthGRUG",
                    type: "track",
                    title: "Do The Deal",
                    description: "Baron Von Trax",
                    thumbnail: "https://i.scdn.co/image/ab67616d00001e02dd684bb23bf071f7f4c811a8",
                },
                {
                    id: "7183fwCYtpFWrBWamXHU1E",
                    type: "track",
                    title: "one life, might live",
                    description: "Little Simz",
                    thumbnail: "https://i.scdn.co/image/ab67616d00001e02e87c1c709ebcba96c9d7041e",
                },
                {
                    id: "2sFlh6vt8U5TN3rTBFxRBl",
                    type: "track",
                    title: "Trancy Bounce",
                    description: "Sasuma",
                    thumbnail: "https://i.scdn.co/image/ab67616d00001e0272574d0cb19beda99975c159",
                },
                {
                    id: "4iqtDvbICWuBERMTz9cz41",
                    type: "track",
                    title: "Call Me",
                    description: "Marlon Hoffstadt, DJ Daddy Trance",
                    thumbnail: "https://i.scdn.co/image/ab67616d00001e0274699ccf53c5f0f8cb38711d",
                },
            ],
            rules: [
                { name: "Danceability", value: 99 },
                { name: "Mood", value: [81.43129712752713, 19.326938726963142] },
            ],
            trackHistory: [
                {
                    tracks: [
                        "5ycy4ms054XrdXAbHkPuZj",
                        "3GH8eacML602pwvPdKiLAc",
                        "1ouEtOzJgtIBshX4q4kLFU",
                        "0tTkmkQFLyLtyPZTcy0yHy",
                        "0Wd754HFjUPXozX3B2yRyf",
                    ],
                    added_at: 1730140076818,
                },
                {
                    tracks: [
                        "1qyns5MRU7J7mkAgUkTtEY",
                        "4IvROGodT8xOhTvKEGWIpr",
                        "5h3wNrQxbVKKdoDdzbFCb3",
                        "0RVEAF3XFF2dZFhI8O58JF",
                        "5azE1OgMa2Zdd5qEOmOpps",
                    ],
                    added_at: 1730153775987,
                },
                {
                    tracks: [
                        "3Fhbokt5gD0lh4GEUTcpYC",
                        "73QPLK0uLE4JOF2Gr70QbM",
                        "0yxGKAoQbBUh2u2FGghUzC",
                        "5AWGyFvWNof3Knq7QrN3jD",
                        "3pqvIzV7DIS9orbtKlHAal",
                    ],
                    added_at: 1730326574512,
                },
                {
                    tracks: [
                        "249ToFH497hLGmFUmYH79f",
                        "2UrmuJiYa7GYEkgBNvRDdE",
                        "3ij0X4ItMOoozVcQh3q7Jg",
                        "3IC5oKi7Fo7OLJlYj3fSOp",
                        "51sh8Q7VYcknNufSo97UVF",
                    ],
                    added_at: 1730758575271,
                },
                {
                    tracks: [
                        "1Rq3Yz9pFEpQbYyjZ8yuKT",
                        "2wQzrsaE8GyfI67WN5wmcx",
                        "6BAXywn7SwAV4QlYbS9fFF",
                        "6YxqrwVQamLm3029qHtByh",
                        "1nvoh304h7a0RQgPgquxgZ",
                    ],
                    added_at: 1731358909807,
                },
                {
                    tracks: [
                        "3a9BypAqVxHNCZgHQXfeG7",
                        "2VCNEVHJtAqZLVv3UheSXm",
                        "7xwx05LrizEcCxHrKSj4C1",
                        "5NTrZL3KHZbMagULl1dqXN",
                        "4ReAZJugbi5xpVBI56oFxX",
                    ],
                    added_at: 1731595872989,
                },
                {
                    tracks: [
                        "3UYsJbgJ6EelhHwL00zmwr",
                        "3aBOX8zZPFHEfugtg6Dtch",
                        "0TRacXQJQUwnAexcZJOZ8t",
                        "1mVTQSGoFchL3VVrIa0MeH",
                        "3L8eDRWkchHU0AGv91cTQE",
                    ],
                    added_at: 1731708904233,
                },
                {
                    tracks: [
                        "1GQIKzxlmvW86Mzg5RKP2G",
                        "2FAik0wCT2bEcXMeYhoTkj",
                        "6QrgxKiGjdJ5wOmZvGzWPu",
                        "6yXPnPhj2caXiaXJKSGsSz",
                        "18jcuenWg8hfYdZee2lQfc",
                    ],
                    added_at: 1732572902627,
                },
            ],
            historyToRestore: 7,
            _id: "671fd7ac157ef611f38eddb7",
        },
        {
            playlist_id: "78ibL2hyccvdPv4mKAn9ed",
            lastUpdated: new Date(1730144797124),
            preferences: {
                name: "Boom-Bap-Ballin",
                frequency: "monthly",
                amount: 50,
                on: 0,
            },
            seeds: [
                {
                    id: "59INtpERr4L9x6PSQAFJgM",
                    type: "track",
                    title: "South City Court",
                    description: "Too Many T's",
                    thumbnail: "https://i.scdn.co/image/ab67616d00001e028dfed2aca511d6fa6d444e9e",
                },
                {
                    id: "6qxpnaukVayrQn6ViNvu9I",
                    type: "artist",
                    title: "BigXthaPlug",
                    description: "980.2 k followers",
                    thumbnail: "https://i.scdn.co/image/ab6761610000517467d85a54c927a30a7c94138d",
                },
                {
                    id: "2gcpea4r4aH9Hm0Ty0kmNt",
                    type: "track",
                    title: "Fruchtsaft",
                    description: "LAYLA",
                    thumbnail: "https://i.scdn.co/image/ab67616d00001e02785f9cdda48d87d8b3757ae7",
                },
                {
                    id: "48ZUwXrEOhaXLCxvmRYhZv",
                    type: "track",
                    title: "Don't Sweat The Technique",
                    description: "Eric B. & Rakim",
                    thumbnail: "https://i.scdn.co/image/ab67616d00001e02d552416cafb8792b442655b2",
                },
            ],
            rules: [{ name: "Tempo", value: 90 }],
            trackHistory: [
                {
                    tracks: [
                        "1hJSZ6on25EFwgpKVPdsgy",
                        "4NZXjtc5TsHpX8XQ12c941",
                        "3r8FNirjAPzffGLlmaSgbL",
                        "1qJGJR5DXftoDjeNjNvIDy",
                        "2wdZZ1o4YiOyMSvlQoTXAs",
                        "5nFqMzU83pOOQBD3qLrDbY",
                        "2LhhnqrHPWvXYveZVHLKrd",
                        "5jMnDNdpFkR1rrAo6ktupW",
                        "2azuGP6VvkvdpGDcjpuvd5",
                        "4zRUq4vXHXFucRfRgJSpUy",
                        "3X414ZlCf5U7pcpIaIcUkT",
                        "1fotoYONO343JjbC8XvPSl",
                        "5ql5g268Rj81Mp5CSN17jl",
                        "4M7qmwRv0hPRu4o5LwL4qH",
                        "38o21SqSUmlvJD06Xbb8Hu",
                        "389SVIywlPU6jJyPWMomf7",
                        "2cL6SckJxbEWbi4l0mXFsv",
                        "3S460ibhLhBDHhWvID34ws",
                        "1rJM37Dd4OcSJvzI84yCcP",
                        "4C7Ss9bTPOWJMh3rarF1mN",
                        "0T8ONxWaDqKtbWGxsr5Ba6",
                        "7xAj1FG7hDGLg0qw9805Kr",
                        "5dfutlUaIcA78MDq6fbkDf",
                        "29yNeKqdKGSz2T8EBZCcxH",
                        "5fxq6aZMbSLjQCu14qxqag",
                        "3yjVsUq8psgcHm8SQrZ8i4",
                        "4RqhXN0jEaWh36mh3FgDye",
                        "1cxyAjP3hZ04AhK8NRL9rI",
                        "347YDsxprbGCtoZylsyBAp",
                        "746X8HvYnbrMIqHl9R4QP1",
                        "26RatbbtOHIO6N0KkZKJpl",
                        "4POLSyF3Vr8ZP14AKyCAXf",
                        "5EY7EoleIBgzMJMTjLYbZg",
                        "6PpcSa4TSAGI1sERRKopbT",
                        "32rUiWgyd3Du6uJe0CbXR3",
                        "1vkpe29DP5EvAxYnWVq5C1",
                        "4gQdwwPXSXnDkUh4jYqLoC",
                        "3eh51r6rFWAlGQRlHx9QnQ",
                        "7Lbuvj2QDW80Jb6HiGs8jX",
                        "7jWHehRwt5uxfwYWDcCzJA",
                        "4Q4oMZeR2j5y8HIkSehAZc",
                        "0gytHb5lNdCSeURIIY99yM",
                        "2DisArJavdw7vPotQr9b9H",
                        "1yfKakY4rvI17lk20ekuRA",
                        "7rjYMLk1iQ0cCPFoBrGsSO",
                        "7EoVZAPHRQpeJvuy6yd9Ut",
                        "67mtN6BlsJR0LVyzvNZnGt",
                        "49bbIzbA0MoNxUQG4J9KcG",
                        "4qfUlchVD7WM4JhA5xio6m",
                        "1WIZiOuNO3woKfdlSK2gNn",
                    ],
                    added_at: 1730140550081,
                },
                {
                    tracks: [
                        "5g0WxEuvkj45r3jfcCU78Y",
                        "1m50R7olwYoVVbt2t9I9gJ",
                        "6RXYuVDMvzJlK9Doe4HHxV",
                        "3nqoRpgYMGMXEYZDadLtHL",
                        "5wMaeveG7gyj8OXBmjNgAz",
                        "4TyZQTWKu95yUinsu2qkIa",
                        "4FUfzEs2pu0XAxUosgzAJT",
                        "3DfclONnsDo1FksdD3Iguj",
                        "2hcYH0zDqcxYT4HUEfgpAX",
                        "5vuFJQKbtg4ClgdgLR6OVk",
                        "0jLSeolrFXlzTQQjAOAWli",
                        "4hQQDL8KfmqkD7m1WnjDyU",
                        "7Lhog4pElvGOETKuj7nCK9",
                        "3AEChkx5lDSP9tckzl4cJJ",
                        "70qdjjlJ1XCSCw7r6E2WU5",
                        "72UidoFGPPqJduJn9YAyYk",
                        "26XvzvPD9twtlYhDqSpqP6",
                        "4Qk1JxvjzD3rd6J6DfIxJA",
                        "3rD83UaORNhRgKq0OkdDIt",
                        "18F8dM4MPg5M6ie18cHaMq",
                        "2nRv5oZeCz4pXdF9XLkTbd",
                        "1BTtTuQeVzFqqaiZY2xTp9",
                        "0snDRsjNRMJhm7SVja8l6J",
                        "2W58HMaCbjcUfZnZaeHtcC",
                        "0IVAlb0cFCH1cQ974iR1TU",
                        "6SI4JD7iyQ0rrudhCNtMv0",
                        "5ti4mhcnlDhC2J1CYUYhWQ",
                        "1LM6EReMkAxuDXDF26ekl2",
                        "28AvvchUP85ihRe9xCzcfB",
                        "3ipzZgH1766XXRamVwk1Iw",
                        "6Pv1ZyPXs18xuiwJdoDarC",
                        "4PcO1Spa5Vy5zFePNzTRap",
                        "3ZYzL6Uqir123wh4ZQ7Hur",
                        "0wXu4946Y38BdFePyCnjZE",
                        "7a4rpjBbiBYJshwBFJ7kVI",
                        "3pHD71xpAn0TwwDbfhdbUE",
                        "36kAdDagQXFuXk1T3BQYGi",
                        "1ThVEm8dOdjEStCwspnmPR",
                        "6IhnZQM1zVB7AmPrTxrYDK",
                        "7g5r6WXipOFABCiVnmeFfO",
                        "5JS1gz9zP4GTy0LZYvSeUK",
                        "6sghEq6gM4Ugadwa12H7Sa",
                        "7mVu7ZhScNi6NilUJos3Z5",
                        "4EUMuzx1BKnyW9Exyds8xL",
                        "5mx5lXpouQi2BnlGTHFvQZ",
                        "0EhR86E9VVSzG0LdEer4lF",
                        "7DTlsMOQjGysXHpwwpHuPl",
                        "1z3X66BhWXsSr7lHlSCiDW",
                        "4u7Dz4YJZth00l3PMxShWX",
                        "15zysgHJAJMMFLxRqAkk2o",
                    ],
                    added_at: 1730144797122,
                },
            ],
            historyToRestore: 1,
            _id: "671fd986157ef611f38eddca",
        },
    ],
};

export default exampleUser;
