const genres = [
    "acoustic",
    "afrobeat",
    "alt-rock",
    "alternative",
    "ambient",
    "anime",
    "black-metal",
    "bluegrass",
    "blues",
    "bossanova",
    "brazil",
    "breakbeat",
    "british",
    "cantopop",
    "chicago-house",
    "children",
    "chill",
    "classical",
    "club",
    "comedy",
    "country",
    "dance",
    "dancehall",
    "death-metal",
    "deep-house",
    "detroit-techno",
    "disco",
    "disney",
    "drum-and-bass",
    "dub",
    "dubstep",
    "edm",
    "electro",
    "electronic",
    "emo",
    "folk",
    "forro",
    "french",
    "funk",
    "garage",
    "german",
    "gospel",
    "goth",
    "grindcore",
    "groove",
    "grunge",
    "guitar",
    "happy",
    "hard-rock",
    "hardcore",
    "hardstyle",
    "heavy-metal",
    "hip-hop",
    "holidays",
    "honky-tonk",
    "house",
    "idm",
    "indian",
    "indie",
    "indie-pop",
    "industrial",
    "iranian",
    "j-dance",
    "j-idol",
    "j-pop",
    "j-rock",
    "jazz",
    "k-pop",
    "kids",
    "latin",
    "latino",
    "malay",
    "mandopop",
    "metal",
    "metal-misc",
    "metalcore",
    "minimal-techno",
    "movies",
    "mpb",
    "new-age",
    "new-release",
    "opera",
    "pagode",
    "party",
    "philippines-opm",
    "piano",
    "pop",
    "pop-film",
    "post-dubstep",
    "power-pop",
    "progressive-house",
    "psych-rock",
    "punk",
    "punk-rock",
    "r-n-b",
    "rainy-day",
    "reggae",
    "reggaeton",
    "road-trip",
    "rock",
    "rock-n-roll",
    "rockabilly",
    "romance",
    "sad",
    "salsa",
    "samba",
    "sertanejo",
    "show-tunes",
    "singer-songwriter",
    "ska",
    "sleep",
    "songwriter",
    "soul",
    "soundtracks",
    "spanish",
    "study",
    "summer",
    "swedish",
    "synth-pop",
    "tango",
    "techno",
    "trance",
    "trip-hop",
    "turkish",
    "work-out",
    "world-music",
];

const getSeedsFromItems = (items) => {
    const seeds = items.map((item) => {
        const seed = {
            spotify: "todo: find genre links",
            id: item.title,
            title: item.title,
            description: item.type,
            type: item.type,
            thumbnail: "",
        };
        return seed;
    });
    return seeds;
};

console.log(getSeedsFromItems(genres));

const erfahrung = [
    {
        role: "Supervisor - MedialabSupervisor - Medialab",
        company: "Hochschule für Gestaltung Schwäbisch Gmünd · Vollzeit ",
        duration: "Sept. 2021-Sept. 2023 · 2 Jahre 1 Monat",
        experiences: `<ul>
                <li>Lecturing Programming Languages, fundamentals of component based web development with svelte</li>
                <li>Suppporting and advising students on technical and design related issues in their projects</li>
                <li>Managing the hardware-library for student projects</li>
                `,
    },
];

// Supervisor - MedialabSupervisor - Medialab
// Hochschule für Gestaltung Schwäbisch Gmünd · VollzeitHochschule für Gestaltung Schwäbisch Gmünd · Vollzeit Sept. 2021–Sept. 2023 · 2 Jahre 1 MonatSept. 2021–Sept. 2023 · 2 Jahre 1 Monat Schwäbisch Gmünd, Baden-Württemberg, Deutschland · Vor OrtSchwäbisch Gmünd, Baden-Württemberg, Deutschland · Vor Ort

//         - Lecturing Programming Languages, fundamentals of component based web development with svelte
//         - Suppporting and advising students on technical and design related issues in their projects
//         - Managing the hardware-library for student projects
